# 예외와 트랜잭션 커밋, 롤백 - 활용
스프링은 왜 체크 예외는 커밋하고, 언체크(런타임) 예외는 롤백할까?
스프링은 기본적으로 체크예외는 비즈니스 의미가 있을 때 사용하고, 런타임(언체크) 예외는 복구 불가능한
예외로 가정한다.
- 체크 예외 : 비즈니스 의미가 있을 떄 사용
- 언체크 예외 : 복구 불가능한 예외

참고로 꼭 이런 정책을 따를 필요는 없다. `rollbackFor` 옵션을 사용해 체크 예외도 롤백하면 된다.

비즈니스 예외란 무엇일까?

## 비즈니스 요구사항
주문을 하는데 상황에 따라 다음과 같이 조치한다.
1. 정상 : 주문시 결제를 성공하면 주문 데이터를 저장하고 결제 상태를 `완료`로 처리한다.
2. 시스템 예외 : 주문시 내부에 복구 불가능한 예외가 발생하면 전체 데이터를 롤백한다.
3. 비즈니스 예외 : 주문시 결제 잔고가 부족하면 주문 데이터를 저장하고, 결제 상태를 `대기`로 처리한다.
    - 이 경우 고객에게 잔고 부족을 알리고 별도의 계좌로 입금하도록 안내한다.

- 결제 잔고가 부족하면 `NotEnoughMoneyException`이라는 체크 예외가 발생했다고 가정
- 이 예외는 시스템에 문제가 있어서 발생하는 시스템 예외가 아니다. 시스템은 정상 동작했지만, 비즈니스
상황에서 문제가 때문에 발생한 예외이다.
- 고객의 잔고가 부족한 것은 시스템에 문제가 있는 것이 아닌 비즈니스 상황이 예외인 것이다.
- 이런 예외를 비즈니스 예외라 한다.
- 비즈니스 예외는 매우 중요하고, 반드시 처리해야 하는 경우가 많으므로 체크예외를 고려할 수 있다.

## NotEnoughMoneyException
```java
package hello.springtx.order;

public class NotEnoughMoneyException extends Exception {
   public NotEnoughMoneyException(String message) {
      super(message);
   }
}
```
- 결제 잔고가 부족하면 발생하는 비즈니스 예외이다. `Exception`을 상속 받아서 체크 예외가 된다.

## Order
```java
package hello.springtx.order;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "orders")
@Getter
@Setter
public class Order {
   @Id
   @GeneratedValue
   private Long id;
   private String username; //정상, 예외, 잔고부족
   private String payStatus; //대기, 완료
}
```
- JPA를 사용하는 `Order` 엔티티이다.
- 주의 : `@Table(name = "orders")` - 테이블 이름을 지정하지 않으면 `order`가 되는데
`order`는 데이터베이스 예약어 (`order by`)여서 사용할 수 없다. 그래서 `orders`로
따로 지정해주었다.

## OrderRepository
```java
package hello.springtx.order;

import org.springframework.data.jpa.repository.JpaRepository;

public interface OrderRepository extends JpaRepository<Order, Long> {
}
```
- 스프링 데이터 JPA를 사용한다.

## OrderService
```java
package hello.springtx.order;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
@RequiredArgsConstructor
public class OrderService {
   private final OrderRepository orderRepository;

   //JPA는 트랜잭션 커밋 시점에 Order 데이터를 DB에 반영한다.
   @Transactional
   public void order(Order order) throws NotEnoughMoneyException {
      log.info("order 호출");
      orderRepository.save(order);
      log.info("결제 프로세스 진입");
      if (order.getUsername().equals("예외")) {
         log.info("시스템 예외 발생");
         throw new RuntimeException("시스템 예외");
      } else if (order.getUsername().equals("잔고부족")) {
         log.info("잔고 부족 비즈니스 예외 발생");
         order.setPayStatus("대기");
         throw new NotEnoughMoneyException("잔고가 부족합니다");
      } else {
         //정상 승인
         log.info("정상 승인");
         order.setPayStatus("완료");
      }
      log.info("결제 프로세스 완료");
   }
}
```
- 여러 상황을 만들기 위해서 사용자 이름 (`username`)에 따라서 처리 프로세스를 다르게 했다.
  - `기본` : `payStatus`를 `완료`상태로 처리하고 정상 처리된다.
  - `예외` : `RuntimeException("시스템 예외")`런타임 예외가 발생한다.
  - `잔고부족` :
    - `payStatus`를 `대기`상태로 처리한다.
    - `NotEnoughMoneyException("잔고가 부족합니다")`체크 예외가 발생한다.
    - 잔고 부족은 `payStatus`를 `대기`상태로 두고, 체크 예외가 발생하지만, `order` 데이터는
      커밋되기를 기대한다.

## OrderServiceTest
```java
package hello.springtx.order;

import lombok.extern.slf4j.Slf4j;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Optional;

import static org.assertj.core.api.Assertions.*;

@Slf4j
@SpringBootTest
class OrderServiceTest {
   @Autowired
   OrderService orderService;
   @Autowired
   OrderRepository orderRepository;

   @Test
   void complete() throws NotEnoughMoneyException {
      //given
      Order order = new Order();
      order.setUsername("정상");
      //when
      orderService.order(order);
      //then
      Order findOrder = orderRepository.findById(order.getId()).get();
      assertThat(findOrder.getPayStatus()).isEqualTo("완료");
   }

   @Test
   void runtimeException() {
      //given
      Order order = new Order();
      order.setUsername("예외");
      //when, then
      assertThatThrownBy(() -> orderService.order(order))
              .isInstanceOf(RuntimeException.class);
      //then: 롤백되었으므로 데이터가 없어야 한다.
      Optional<Order> orderOptional =
              orderRepository.findById(order.getId());
      assertThat(orderOptional.isEmpty()).isTrue();
   }

   @Test
   void bizException() {
      //given
      Order order = new Order();
      order.setUsername("잔고부족");
      //when
      try {
         orderService.order(order);
         fail("잔고 부족 예외가 발생해야 합니다.");
      } catch (NotEnoughMoneyException e) {
         log.info("고객에게 잔고 부족을 알리고 별도의 계좌로 입금하도록 안내");
      }
      //then
      Order findOrder = orderRepository.findById(order.getId()).get();
      assertThat(findOrder.getPayStatus()).isEqualTo("대기");
   }
}
```
`application.properties`
```properties
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG
#JPA log
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
logging.level.org.hibernate.resource.transaction=DEBUG
#JPA SQL
logging.level.org.hibernate.SQL=DEBUG
```
- 로그를 추가하여 JPA가 실행하는 SQL을 로그로 확인할 수 있다.
- 지금처럼 메모리 DB를 통해 테스트를 수행하면 테이블 자동 옵션에 활성화된다. (엔티티 정보 참고)
- 테이블 자동생성 옵션 : `spring.jpa.hibernate.ddl-auto`
  - `none` : 테이블을 생성하지 않는다.
  - `create` : 애플리케이션 시작 시점에 테이블을 생성한다.
- 실행 SQL : `create table orders...`

### complete()
- 사용자 이름을 `정상`으로 설정했다. 모든 프로세스가 정상 수행된다.
- 다음을 통해서 데이터가 `완료` 상태로 저장 되었는지 검증한다.<br>
`assertThat(findOrder.getPayStatus()).isEqualTo("완료");`

### runtimeException()
- 사용자 이름을 `예외`로 설정했다.
- `RuntimeException("시스템 예외")`이 발생한다.
- 런타임 예외로 롤백이 수행되었기 때문에 `Order`데이터가 비어 있는 것을 확인할 수 있다.

### bizException()
- 사용자 이름을 `잔고부족`로 설정했다.
- `NotEnoughMoneyException("잔고가 부족합니다.")`이 발생한다.
- 체크 예외로 커밋이 수행되었기 때문에 `Order` 데이터가 저장된다.
- 다음을 통해서 데이터가 `대기` 상태로 잘 저장되었는지 검증한다.<br>
`assertThat(findOrder.getPayStatus()).isEqualTo("대기");`

### 정리
- `NotEnoughMoneyException`은 시스템에 문제가 발생한 것이 아니라, 비즈니스 문제 상황을 에외를 통해
알려준다. 마치 예외가 리턴값처럼 사용된다. 따라서 이 경우에는 트랜잭션을 커밋하는 것이 맞다. 이 경우
롤백하면 생성한 `Order` 자체가 사라진다. 그러면 고객에게 잔고 부족을 알리고 별도의 계좌로 입금하도록 
안내해도 주문 (`Order`) 자체가 사라지기 때문에 문제가 된다.
- 그런데 비즈니스 상황에 따라 체크 예외의 경우에도 트랜잭션을 커밋하지 않고, 롤백하고 싶을 수도 있다.
이 때는 `rollbackFor` 옵션을 사용하면 된다.
- 런타임 예외는 항상 롤백된다. 체크 예외의 경우 `rollbackFor` 옵션을 사용해서 비즈니스 상황에
따라서 커밋과 롤백을 선택하면 된다.
